### ISSUE TITLE
Error in the extension, gives an error

### ISSUE THREAD

**Issue by Gvidon12** [azate/anti-random.org#12]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
Error in the extension, gives an error

**Comment by Gvidon12** [comment]
<img width="664" alt="skrin" src="https://github.com/azate/anti-random.org/assets/152395786/72c9fa32-f43c-4828-a331-0124532035af">

**Comment by Gvidon12** [comment]
Please tell me how to fix this problem?

**Comment by hz61p1** [comment]
@Gvidon12 I need to update the source code and add support for manifest v3, I was planning to add support for other browsers as well. But now I am not interested in supporting this project because of its low popularity in the open media space, but statistically it is actively used and I assume not for benevolent purposes

**Comment by hz61p1** [comment]
@Gvidon12 A new version has been released, try it
